trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
  persistCredentials: true
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    set -eo pipefail
    pwd
    ls
    npm ci
    npm run docs:build
    cp -r src/.vuepress/dist $(Build.ArtifactStagingDirectory) 
    git checkout origin/gh-pages
    
    # Remove the old site content
    rm -r ./*
    cp -r $(Build.ArtifactStagingDirectory)/dist/* . 
    echo "docs.choreo.dev" > CNAME

    git config --global user.email "choreo-cicd@wso2.com"
    git config --global user.name "Choreo CI Agent"

    git add .
    git commit -m 'Updating documentation in $(Build.BuildNumber)'
    git push  origin  HEAD:gh-pages

  displayName: 'Choreo documentation build and publish'
